---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crowdsec

helmCharts:
  - name: crowdsec
    repo: https://crowdsecurity.github.io/helm-charts
    version: "0.13.0"
    releaseName: crowdsec
    namespace: crowdsec
    valuesFile: values.yaml
    includeCRDs: true
