---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea-actions

resources:
  - namespace.yaml

helmCharts:
  - name: actions
    repo: oci://docker.gitea.com/charts
    version: "0.1.2"
    releaseName: gitea-actions
    namespace: gitea-actions
    valuesFile: values.yaml
