---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: ai
spec:
  volumeName: pvc-8f14bed0-7354-45ea-833f-df29bc32eb0c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-open-webui
  namespace: ai
spec:
  volumeName: pvc-56f77b6d-7345-4265-9402-2a1ae622b739
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-pipelines
  namespace: ai
spec:
  storageClassName: nfs
  volumeName: pvc-54fe6468-da51-46fe-9c86-cbc0e69eab4a
