---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

helmCharts:
  - name: immich
    repo: oci://ghcr.io/immich-app/immich-charts
    version: "0.11.1"
    releaseName: immich
    namespace: immich
    valuesFile: values.yaml

resources:
  - config/cnpg-cluster.yaml
  - config/library-pvc.yaml
