---
grafana:
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-lan-only@kubernetescrd
    hosts:
      - grafana.mirkwood.casa
  persistence:
    enabled: true
    storageClassName: nfs
    size: 10Gi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      traefik:
        gnetId: 17346
        datasource: Prometheus
      cert-manager:
        gnetId: 11001
        datasource: Prometheus

prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-lan-only@kubernetescrd
    hosts:
      - prometheus.mirkwood.casa
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          resources:
            requests:
              storage: 50Gi
    additionalServiceMonitors:
      - name: traefik
        selector:
          matchLabels:
            app.kubernetes.io/name: traefik
        namespaceSelector:
          matchNames:
            - traefik
        endpoints:
          - port: metrics
            path: /metrics

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-lan-only@kubernetescrd
    hosts:
      - alertmanager.mirkwood.casa
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          resources:
            requests:
              storage: 5Gi
