---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: cubie-cp01
auto: off
---
machine:
  nodeLabels:
    workload.gitea-runner: "true"
  network:
    interfaces:
      - interface: ens18
        addresses:
          - 10.69.10.236/23
        routes:
          - network: 0.0.0.0/0
            gateway: 10.69.10.1
        dhcp: false
