---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

helmCharts:
  - name: ollama
    repo: https://otwld.github.io/ollama-helm
    version: "1.65.0"
    releaseName: ollama
    namespace: ai
    valuesFile: ollama-values.yaml
    includeCRDs: true

  - name: open-webui
    repo: https://open-webui.github.io/helm-charts
    version: "14.11.0"
    releaseName: ai
    namespace: ai
    valuesFile: open-webui-values.yaml
    includeCRDs: true
