---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

helmCharts:
  - name: ollama
    repo: https://otwld.github.io/ollama-helm
    version: "1.58.0"
    releaseName: ollama
    namespace: ai
    valuesFile: ollama-values.yaml
    includeCRDs: true

  - name: open-webui
    repo: https://open-webui.github.io/helm-charts
    version: "14.8.0"
    releaseName: ai
    namespace: ai
    valuesFile: open-webui-values.yaml
    includeCRDs: true

  - name: n8n
    repo: https://community-charts.github.io/helm-charts
    version: "1.16.46"
    releaseName: n8n
    namespace: ai
    valuesFile: n8n-values.yaml

resources:
  - config/n8n-cnpg-cluster.yaml
