---
deployment:
  replicas: 1

service:
  type: LoadBalancer
  annotations:
    # MetalLB annotation: pin to specific IP if desired, or remove to auto-assign.
    metallb.universe.tf/loadBalancerIPs: "10.69.11.42"

ports:
  web:
    port: 8000
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    port: 8443

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true

logs:
  general:
    level: INFO
  access:
    enabled: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
