---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: "9.0.5"
    releaseName: nextcloud
    namespace: nextcloud
    valuesFile: values.yaml

resources:
  - config/cnpg-cluster.yaml
