---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: external
spec:
  ports:
    - port: 30013
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: jellyfin
  namespace: external
  labels:
    kubernetes.io/service-name: jellyfin
addressType: IPv4
endpoints:
  - addresses:
      - 10.69.10.3
ports:
  - port: 30013
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: external
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - play.mirkwood.casa
  rules:
    - host: play.mirkwood.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 30013
