---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea

helmCharts:
  - name: gitea
    repo: oci://docker.gitea.com/charts
    version: "12.7.0"
    releaseName: gitea
    namespace: gitea
    valuesFile: values.yaml

resources:
  - config/cnpg-cluster.yaml
  - config/ingressroutetcp-ssh.yaml
