---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "mirkwood.casa"
    - "*.mirkwood.casa"
    - "vunder.io"
    - "*.vunder.io"
  duration: 2160h # 90 days
  renewBefore: 360h # renew 15 days before expiry
